"""
backend/config.py — Re-exports RAG configuration from main.py,
keeping main.py as the single source of truth.
"""

import main

CACHE_DIR = main.CACHE_DIR
EMBEDDING_MODEL = main.EMBEDDING_MODEL
LLM_REPO_ID = main.LLM_REPO_ID
RETRIEVER_K = main.RETRIEVER_K
RELEVANCE_SCORE_THRESHOLD = main.RELEVANCE_SCORE_THRESHOLD
CHUNK_SIZE = main.CHUNK_SIZE
CHUNK_OVERLAP = main.CHUNK_OVERLAP
MAX_QUESTION_LENGTH = main.MAX_QUESTION_LENGTH
CACHE_SCHEMA_VERSION = main.CACHE_SCHEMA_VERSION
PREFERRED_LANGUAGES = main.PREFERRED_LANGUAGES
